/**
 * Print & Receipt helper for Small Business Master Calculator
 */
import { formatCurrency, formatDate } from './formatters';

export const printInvoiceReceipt = (invoiceData, currencySymbol = '₹') => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to print receipt/invoice.');
    return;
  }

  const itemsHtml = (invoiceData.items || []).map((item, idx) => `
    <tr>
      <td style="padding: 8px; border-bottom: 1px dashed #ccc;">${idx + 1}</td>
      <td style="padding: 8px; border-bottom: 1px dashed #ccc; font-weight: bold;">${item.name || 'Item'}</td>
      <td style="padding: 8px; border-bottom: 1px dashed #ccc; text-align: right;">${item.qty || 1} ${item.unit || ''}</td>
      <td style="padding: 8px; border-bottom: 1px dashed #ccc; text-align: right;">${formatCurrency(item.rate, currencySymbol)}</td>
      <td style="padding: 8px; border-bottom: 1px dashed #ccc; text-align: right; font-weight: bold;">${formatCurrency((item.qty || 1) * (item.rate || 0), currencySymbol)}</td>
    </tr>
  `).join('');

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Receipt - ${invoiceData.shopName || 'Business'}</title>
      <style>
        body {
          font-family: 'Courier New', Courier, monospace;
          background: #fdfbf7;
          color: #111;
          margin: 0;
          padding: 20px;
        }
        .ticket {
          max-width: 400px;
          margin: 0 auto;
          background: #fff;
          padding: 24px;
          border: 1px solid #ddd;
          box-shadow: 0 4px 10px rgba(0,0,0,0.1);
        }
        .header {
          text-align: center;
          border-bottom: 2px dashed #000;
          padding-bottom: 12px;
          margin-bottom: 16px;
        }
        .header h2 {
          margin: 0 0 6px 0;
          font-size: 22px;
          text-transform: uppercase;
        }
        .info {
          font-size: 13px;
          margin-bottom: 16px;
          line-height: 1.4;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          font-size: 13px;
          margin-bottom: 16px;
        }
        th {
          text-align: left;
          border-bottom: 2px solid #000;
          padding: 6px 8px;
        }
        .totals {
          border-top: 2px dashed #000;
          padding-top: 12px;
          font-size: 14px;
        }
        .row {
          display: flex;
          justify-content: space-between;
          margin-bottom: 6px;
        }
        .grand-total {
          font-size: 18px;
          font-weight: bold;
          border-top: 2px solid #000;
          border-bottom: 2px solid #000;
          padding: 8px 0;
          margin-top: 8px;
        }
        .footer {
          text-align: center;
          margin-top: 24px;
          font-size: 12px;
          color: #555;
        }
      </style>
    </head>
    <body>
      <div class="ticket">
        <div class="header">
          <h2>${invoiceData.shopName || 'CASH RECEIPT'}</h2>
          <div>Small Business Master Receipt</div>
        </div>
        <div class="info">
          <div><strong>Date:</strong> ${formatDate(invoiceData.date || new Date())}</div>
          <div><strong>Invoice #:</strong> ${invoiceData.invoiceNo || 'INV-1001'}</div>
          ${invoiceData.customerName ? `<div><strong>Customer:</strong> ${invoiceData.customerName}</div>` : ''}
        </div>
        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>Item</th>
              <th style="text-align: right;">Qty</th>
              <th style="text-align: right;">Rate</th>
              <th style="text-align: right;">Total</th>
            </tr>
          </thead>
          <tbody>
            ${itemsHtml}
          </tbody>
        </table>
        <div class="totals">
          <div class="row">
            <span>Subtotal:</span>
            <span>${formatCurrency(invoiceData.subtotal || 0, currencySymbol)}</span>
          </div>
          ${invoiceData.discount > 0 ? `
          <div class="row" style="color: red;">
            <span>Discount:</span>
            <span>-${formatCurrency(invoiceData.discount, currencySymbol)}</span>
          </div>
          ` : ''}
          <div class="row grand-total">
            <span>GRAND TOTAL:</span>
            <span>${formatCurrency(invoiceData.grandTotal || 0, currencySymbol)}</span>
          </div>
        </div>
        <div class="footer">
          *** Thank You! Visit Again ***<br/>
          Generated by Small Business Master Calculator
        </div>
      </div>
      <script>
        window.onload = function() {
          window.print();
        };
      </script>
    </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
};

export const generateThermalPrintReceipt = printInvoiceReceipt;
